---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: php-fpm
  name: php-fpm
spec:
  replicas: 3
  template:
    metadata:
      name: php-fpm
      labels:
        app: php-fpm
    spec:
      volumes:
        - name: php-fpm-conf
          configMap:
            name: php-fpm-conf
        - name: php-fpm-pools-conf
          configMap:
            name: php-fpm-pools-conf
      containers:
        - name: php-fpm
          image: php:7-fpm-alpine
          imagePullPolicy: Always
          ports:
            - name: fpm
              containerPort: 9000
          volumeMounts:
            - name: php-fpm-conf
              mountPath: /etc/php/7.0/fpm/php-fpm.conf
            - name: php-fpm-pools-conf
              mountPath: /etc/php/7.0/fpm/pool.d/
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m"
            limits:
              memory: "5000Mi"
              cpu: "500m"
